_target_: src.models.rsna_module.RSNALitModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0005
  momentum: 0.9

scheduler:

net:
  _target_: src.models.components.resnet.ResNet18
  num_classes: 2
  in_channels: 1
